### ISSUE TITLE
MathJax submodule is broken

### ISSUE THREAD

**Issue by 20after4** [DPRL/min#1]
recursive submodule update breaks on mathjax

**Comment by physikerwelt** [comment]
see also http://bots.wmflabs.org/~wm-bot/logs/%23wikimedia-releng/20150126.txt

**Comment by physikerwelt** [comment]
@rlaz Thanks for correcting the URL. However the github repository is still broken. To correct that you need either to remove the submodule (https://github.com/physikerwelt/min/commit/0718dd0cb65dba750baa62361f9e8f4b9616b74f)
and then optionally add it corretly as done in #2.
If you don't need a MathJax clone in the third_party folder the first step is sufficient.

**Comment by rlaz** [comment]
@moritz The 'MathJax' subdirectory is empty, and isn't needed to run the 
application. So I have removed it from the main 'min' repository on GitHub.

If min continues to cause problems for you, please feel free to take min 
offline from your environement until we've made the necessary updates on 
our end so that the system is both more complete and hopefully a bit 
more robust.

On 1/28/15 5:19 AM, Moritz Schubotz wrote:

> @rlaz https://github.com/rlaz Thanks for correcting the URL. However 
> the github repository is still broken. To correct that you need either 
> to remove the submodule (physikerwelt@0718dd0 
> https://github.com/physikerwelt/min/commit/0718dd0cb65dba750baa62361f9e8f4b9616b74f)
> and then optionally add it corretly as done in #2 
> https://github.com/DPRL/min/pull/2.
> If you don't need a MathJax clone in the third_party folder the first 
> step is sufficient.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/DPRL/min/issues/1#issuecomment-71810986.

## 

Richard Zanibbi
Associate Professor, Department of Computer Science
Rochester Institute of Technology, NY, USA
http://www.cs.rit.edu/~rlaz/

**Comment by physikerwelt** [comment]
@rlaz You fixed the problem with this repository in 8832699e89a6e00207d3325a13b27d3e00a93f1a . The rest is not your business I think. So I think this issue should be closed and marked as fixed.

**Comment by 20after4** [comment]
Thanks to both of you for addressing this. <3
